[project]
name = "rolling-bot"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "aiogram>=3.22.0",
    "dotenv>=0.9.9",
    "pydantic-settings>=2.12.0",
]
